apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    dashboards: "grafana"
spec:
  version: "12.4.0"
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: 1password-grafana-admin
                      key: username
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: 1password-grafana-admin
                      key: password
                - name: GF_INSTALL_PLUGINS
                  value: googlecloud-logging-datasource
