---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: uptime-kuma
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
  volumeMode: Filesystem