apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-data
  namespace: semaphore
  labels:
    app: semaphore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi-buckets
  resources:
    requests:
      storage: 2Gi
