apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unas-k8s-kopia-config-rw-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeName: unas-k8s-rw
  storageClassName: nfs
  resources:
    requests:
      storage: 100Gi
