apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  labels:
    app: sftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      containers:
      - name: sftp
        image: despitehowever/sftp:latest
        imagePullPolicy: Always # NOTE: need this for, lazy image tagging
        ports:
        - containerPort: 22
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
          limits:
            cpu: 250m
            memory: 500Mi
        volumeMounts:
        - mountPath: /home/scanner/in
          name: scans-pvc
        - mountPath: "/var/sftp-key"
          name: sftp-hostkey
      volumes:
      - name: scans-pvc
        persistentVolumeClaim:
          claimName: unas-scans-rw-claim
      - name: sftp-hostkey
        secret:
          defaultMode: 0600
          secretName: sftp-hostkey
