apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-system

resources:
  # Install Providers & Secrets
  - resources/providers.yaml 
  - resources/secrets.yaml 
  # DNS
  - resources/cloudflare # NOTE: generated via generate.sh
