apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unas-scans-rw-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: unas-scans-rw
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
