apiVersion: v1
kind: Service
metadata:
  name: beszel-hub
  namespace: beszel
spec:
  ports:
  - name: http
    port: 30333
    targetPort: 30333
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: beszel-hub
  namespace: beszel
subsets:
- addresses:
  - ip: 192.168.10.50
  ports:
  - name: http
    port: 30333
