apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grafana-operator
    releaseName: grafana-operator
    version: v5.15.1
    repo: oci://ghcr.io/grafana/helm-charts
    namespace: monitoring