apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.secrets.password.name }}
  labels:
    {{- include "kopia.labels" . | nindent 4 }}
spec:
  itemPath: "vaults/lab/items/UNAS Backup Password"
