apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

helmCharts:
- name: cert-manager
  includeCRDs: true
  releaseName: cert-manager
  version: v1.16.2
  repo: https://charts.jetstack.io
  valuesFile: values.yaml

resources:
  - resources/secret.yaml
  - resources/letsencrypt-staging.yaml
  - resources/letsencrypt-prod.yaml
