apiVersion: http.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: http-cloudflare
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: cloudflare
      key: token
