---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: cloudflared
spec:
  ports:
    - port: 8006
      targetPort: 8006
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
  namespace: cloudflared
subsets:
  - addresses:
      - ip: 192.168.10.11
      - ip: 192.168.10.12
      - ip: 192.168.10.13
    ports:
      - port: 8006
        protocol: TCP
