apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo

resources:
  - resources/namespace.yml
  - https://github.com/argoproj/argo-workflows/releases/download/v3.6.2/install.yaml
  - resources/argo-ingress.yaml
  - resources/rbac.yaml
  - resources/sa-argo-admin.yaml
  - resources/secret.yaml

patches:
 - target:
      kind: Deployment
      name: argo-server
   path: patches/deployment-argo-server.yaml
