apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-system

resources:
  - resources/envoy-proxy.yaml
  - resources/envoy-patch-policy.yaml
  - resources/gateway.yaml
  - resources/http-redirect.yaml
  - resources/certificates/argocd.yaml
  - resources/certificates/grafana.yaml
  - resources/certificates/prometheus.yaml
  - resources/certificates/uptime.yaml
  - resources/certificates/n8n.yaml
  - resources/certificates/authentik.yaml
  - resources/certificates/garage.yaml
