---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: documents
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
  - vers=3
  - nolock
  csi:
    driver: nfs.csi.k8s.io
    # NOTE: for documents, we want to mount the root of the NFS share as r/o
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    volumeHandle: 192.168.10.5/var/nfs/shared/Documents##
    volumeAttributes:
      server: 192.168.10.5
      share: /var/nfs/shared/Documents