---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: scans
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
  - vers=3
  - nolock
  csi:
    driver: nfs.csi.k8s.io
    # NOTE: for scans, we want to mount the root of the NFS share as r/o
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    volumeHandle: 192.168.10.5/var/nfs/shared/scans##
    volumeAttributes:
      server: 192.168.10.5
      share: /var/nfs/shared/scans