apiVersion: v1
kind: PersistentVolume
metadata:
  name: unas-uptime-rw
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  #persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
  nfs:
    path: /var/nfs/shared/k8s
    server: 192.168.10.5
