apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - onepassword-github-token.yaml

helmCharts:
  - name: gha-runner-scale-set-controller
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.14.2
    releaseName: arc
    namespace: gha-runners
    valuesFile: controller-values.yaml
    includeCRDs: true
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.14.2
    releaseName: self-homelab
    namespace: gha-runners
    valuesFile: runner-values.yaml

patches:
  - target:
      group: actions.github.com
      version: v1alpha1
      kind: AutoscalingRunnerSet
      name: self-homelab
    patch: |-
      apiVersion: actions.github.com/v1alpha1
      kind: AutoscalingRunnerSet
      metadata:
        name: self-homelab
        annotations:
          argocd.argoproj.io/sync-wave: "1"
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: arc-gha-rs-controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: arc-gha-rs-controller
        annotations:
          argocd.argoproj.io/sync-wave: "2"
      spec:
        replicas: 0
