apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - onepassword-github-token.yaml

helmCharts:
  - name: gha-runner-scale-set-controller
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.14.2
    releaseName: arc
    namespace: gha-runners
    valuesFile: controller-values.yaml
    includeCRDs: true
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.14.2
    releaseName: self-homelab
    namespace: gha-runners
    valuesFile: runner-values.yaml
