{{- range .Values.provider.http.dns_records }}
---
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: cloudflare-dns-{{ .name }}
spec:
  providerConfigRef:
    name: http-cloudflare
  forProvider:
    headers:
      Content-Type:
        - application/json
      Authorization:
        - ("Bearer {{ printf "{{ cloudflare:crossplane-system:token }}" }}")
    payload:
      baseUrl: https://api.cloudflare.com/client/v4/zones/f153ce63fd6ad281b16a3c674b51588f/dns_records 
      body: |
        {
          "name": "{{ .name }}",
          "content": "{{ .content }}",
          "comment": "{{ .comment }}",
          "ttl": 0,
          "type": "A"
        }
    mappings:
      - action: CREATE 
        method: "POST" 
        body: |
          {
            comment: .payload.body.comment, 
            content: .payload.body.content, 
            name: .payload.body.name,
            ttl: .payload.body.ttl,
            type: .payload.body.type
          }
        url: .payload.baseUrl
      - action: OBSERVE 
        method: "GET"
        url: (.payload.baseUrl + "/" + (.response.body.result.id|tostring))
      - action: UPDATE
        method: "PATCH"
        body: |
          {
            comment: .payload.body.comment, 
            content: .payload.body.content, 
            name: .payload.body.name,
            ttl: .payload.body.ttl,
            type: .payload.body.type
          }
        url: (.payload.baseUrl + "/" + (.response.body.result.id|tostring))
      - action: REMOVE 
        method: "DELETE"
        url: (.payload.baseUrl + "/" + (.response.body.result.id|tostring))

{{- end }}
