apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-scrape-metrics-svc
spec:
  selector:
    matchLabels:
      prometheus-scrape: "true"
  endpoints:
  - port: metrics
  namespaceSelector:
    any: true
