apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: console-tls
  namespace: gateway
spec:
  secretName: console-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - console.colinbruner.com
