apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-tls
  namespace: gateway-system
spec:
  secretName: uptime-tls
  issuerRef:
    name: letsencrypt-prod      # Promoted from letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - uptime.colinbruner.com
  - uptime-internal.colinbruner.com
