apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authelia

resources:
  - namespace.yaml
  - onepassword-secrets.yaml
  - pvc.yaml
  - configmap-config.yaml
  - configmap-users.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
