apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
  - namespace.yaml
  - authentik-1password.yaml
  - postgres-1password.yaml
  - social-1password.yaml
  - redis.yaml
  - httproute.yaml
  - reference-grant.yaml
  - social-login-blueprint.yaml
  - forward-auth-blueprint.yaml
  - auth-proxy.yaml

helmGlobals:
  chartHome: ../../../packages/helm

helmCharts:
  - name: postgres
    releaseName: postgres
    namespace: authentik
    valuesFile: postgres-values.yaml
  - name: authentik
    repo: https://charts.goauthentik.io
    version: 2025.12.4
    releaseName: authentik
    namespace: authentik
    valuesFile: values.yaml
