apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/storageclass-documents.yaml
  - resources/storageclass-scans.yaml

helmCharts:
  - name: csi-driver-nfs
    releaseName: csi-nfs
    version: 4.11.0
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    namespace: csi-nfs
    valuesFile: values.yaml
