apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pv.yaml
- pvc.yaml
- password.yaml

configMapGenerator:
  - name: kopia-actions
    files:
      - actions/chronos-start.sh
      - actions/chronos-success.sh