---

provider:
  http:
    dns_records:
    - name: "whatever"         # subdomain
      content:                 # one or more IP addresses (creates one A record per IP)
        - "x.x.x.x"
      comment: "some comment"  # arbitrary comment
