apiVersion: v1
kind: PersistentVolume
metadata:
  name: unas-k8s-rw
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions: 
    - hard 
  nfs:
    path: /var/nfs/shared/k8s
    server: 192.168.10.5
