apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unas-k8s-rw-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: unas-k8s-rw
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
