apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.colinbruner.com
  admin.enabled: "false"
  accounts.crossplane: apiKey
  accounts.colin: login, apiKey
  kustomize.buildOptions: "--enable-helm"
  oidc.config: |
    name: Pocket-ID
    issuer: https://auth.colinbruner.com
    clientID: $argocd-pocket-id-oauth:client_id
    clientSecret: $argocd-pocket-id-oauth:client_secret
    requestedScopes:
      - openid
      - profile
      - email
      - groups
    enablePKCEAuthentication: true
