target:
  name: documents
  sourcePath: /Volumes/Documents
  nfsPath: /var/nfs/shared/Documents
  schedule: "15 4 * * *"
  description: "UNAS Documents Backup"

storage:
  gcsBucket: backup-unas-vol-documents-9851

chronos:
  enabled: true
