apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
  - name: grafana-operator
    releaseName: grafana-operator
    repo: oci://ghcr.io/grafana/helm-charts
    version: "5.22.0"
    namespace: monitoring

resources:
  - resources/onepassword-secret.yaml
  - resources/onepassword-pocket-id-oauth.yaml
  - resources/grafana.yaml
  - resources/grafana-httproute.yaml
  - resources/prometheus-httproute.yaml
  - resources/prometheus-scrape.yaml
  - resources/prometheus-servicemonitor.yaml
  - dashboards
  - datasources
