{{- if .Values.chronos.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-actions
  labels:
    {{- include "kopia.labels" . | nindent 4 }}
data:
  chronos-start.sh: |
{{ .Files.Get "files/chronos-start.sh" | indent 4 }}
  chronos-success.sh: |
{{ .Files.Get "files/chronos-success.sh" | indent 4 }}
{{- end }}
