---
# Source: cloudflare-http/templates/dns.yaml
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: cloudflare-dns-sftp
spec:
  providerConfigRef:
    name: http-cloudflare
  forProvider:
    headers:
      Content-Type:
        - application/json
      Authorization:
        - ("Bearer {{ cloudflare:crossplane-system:token }}")
    payload:
      baseUrl: https://api.cloudflare.com/client/v4/zones/f153ce63fd6ad281b16a3c674b51588f/dns_records 
      body: |
        {
          "name": "sftp",
          "content": "192.168.10.241",
          "comment": "SFTP Access for Scans",
          "ttl": 0,
          "type": "A"
        }
    mappings:
      - action: CREATE 
        method: "POST" 
        body: |
          {
            comment: .payload.body.comment, 
            content: .payload.body.content, 
            name: .payload.body.name,
            ttl: .payload.body.ttl,
            type: .payload.body.type
          }
        url: .payload.baseUrl
      - action: OBSERVE 
        method: "GET"
        url: (.payload.baseUrl + "/" + (.response.body.result.id|tostring))
      - action: UPDATE
        method: "PATCH"
        body: |
          {
            comment: .payload.body.comment, 
            content: .payload.body.content, 
            name: .payload.body.name,
            ttl: .payload.body.ttl,
            type: .payload.body.type
          }
        url: (.payload.baseUrl + "/" + (.response.body.result.id|tostring))
      - action: REMOVE 
        method: "DELETE"
        url: (.payload.baseUrl + "/" + (.response.body.result.id|tostring))
---
# Source: cloudflare-http/templates/dns.yaml
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: cloudflare-dns-backups
spec:
  providerConfigRef:
    name: http-cloudflare
  forProvider:
    headers:
      Content-Type:
        - application/json
      Authorization:
        - ("Bearer {{ cloudflare:crossplane-system:token }}")
    payload:
      baseUrl: https://api.cloudflare.com/client/v4/zones/f153ce63fd6ad281b16a3c674b51588f/dns_records 
      body: |
        {
          "name": "backups",
          "content": "192.168.10.240",
          "comment": "Koptia Backups UI",
          "ttl": 0,
          "type": "A"
        }
    mappings:
      - action: CREATE 
        method: "POST" 
        body: |
          {
            comment: .payload.body.comment, 
            content: .payload.body.content, 
            name: .payload.body.name,
            ttl: .payload.body.ttl,
            type: .payload.body.type
          }
        url: .payload.baseUrl
      - action: OBSERVE 
        method: "GET"
        url: (.payload.baseUrl + "/" + (.response.body.result.id|tostring))
      - action: UPDATE
        method: "PATCH"
        body: |
          {
            comment: .payload.body.comment, 
            content: .payload.body.content, 
            name: .payload.body.name,
            ttl: .payload.body.ttl,
            type: .payload.body.type
          }
        url: (.payload.baseUrl + "/" + (.response.body.result.id|tostring))
      - action: REMOVE 
        method: "DELETE"
        url: (.payload.baseUrl + "/" + (.response.body.result.id|tostring))
---
# Source: cloudflare-http/templates/dns.yaml
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: cloudflare-dns-uptime
spec:
  providerConfigRef:
    name: http-cloudflare
  forProvider:
    headers:
      Content-Type:
        - application/json
      Authorization:
        - ("Bearer {{ cloudflare:crossplane-system:token }}")
    payload:
      baseUrl: https://api.cloudflare.com/client/v4/zones/f153ce63fd6ad281b16a3c674b51588f/dns_records 
      body: |
        {
          "name": "uptime",
          "content": "192.168.10.240",
          "comment": "Kuma Uptime UI",
          "ttl": 0,
          "type": "A"
        }
    mappings:
      - action: CREATE 
        method: "POST" 
        body: |
          {
            comment: .payload.body.comment, 
            content: .payload.body.content, 
            name: .payload.body.name,
            ttl: .payload.body.ttl,
            type: .payload.body.type
          }
        url: .payload.baseUrl
      - action: OBSERVE 
        method: "GET"
        url: (.payload.baseUrl + "/" + (.response.body.result.id|tostring))
      - action: UPDATE
        method: "PATCH"
        body: |
          {
            comment: .payload.body.comment, 
            content: .payload.body.content, 
            name: .payload.body.name,
            ttl: .payload.body.ttl,
            type: .payload.body.type
          }
        url: (.payload.baseUrl + "/" + (.response.body.result.id|tostring))
      - action: REMOVE 
        method: "DELETE"
        url: (.payload.baseUrl + "/" + (.response.body.result.id|tostring))
