apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - resources/secret.yaml
  - resources/letsencrypt-staging.yaml
  - resources/letsencrypt-prod.yaml
