apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - resources/argocd-users.yaml
  - resources/argocd-rbac.yaml
  - resources/argocd-httproute.yaml
  - resources/applicationset.yaml
  - resources/onepassword-argocd-pocket-id-oauth.yaml
