apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: semaphore

resources:
  - namespace.yaml
  - resources/onepassword-semaphore.yaml
  - resources/pvc.yaml
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/httproute.yaml
