apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - resources/onepassword-secret.yaml
  - resources/grafana.yaml
  - resources/grafana-httproute.yaml
  - resources/prometheus-httproute.yaml
  - resources/security-policy.yaml
  - dashboards
  - datasources
