apiVersion: v1
kind: PersistentVolume
metadata:
  name: unas-documents-ro
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs
  mountOptions: 
    - hard 
  nfs:
    path: /var/nfs/shared/Documents
    server: 192.168.10.5
