name: Build Container

on:
  push:
    paths:
      - build/**
  pull_request:
  workflow_dispatch:

jobs:
  build_and_push:
    # TODO: iterate and build all Containerfiles in build/
    name: Build Containers
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:build/sftp"
          file: ./Containerfile
          push: true
          # e.g. sftp:latest
          tags: "${{ secrets.DOCKER_USERNAME }}/sftp:latest"
