name: Test
on:
  workflow_dispatch:

jobs:
  build_lxc:
    name: Build LXC
    runs-on: ubuntu-latest
    steps:
      - uses: lkiesow/setup-lxc-container@v1
        id: lxc
        with:
          dist: debian
          release: bookworm

      - name: IP address
        run: |
          echo 'Container IP address: ${{ steps.lxc.outputs.ip }}'

      - name: Test SSH
        run: |
          ssh test echo success

      - name: Run Ansible
        run: |
          echo "[INFO] Runing Ansible"

      - name: Generate rootfs tar
        run: |
          echo "[INFO]: Generating rootfs tar.gz"
