apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  labels:
    app: sftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      containers:
      - name: sftp
        image: despitehowever/sftp:latest
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /home/scanner/in
          name: scans-pvc
        - mountPath: "/var/sftp-key"
          name: sftp-hostkey
          readOnly: true
      volumes:
      - name: scans-pvc
        persistentVolumeClaim:
          claimName: unas-scans-rw-claim
      - name: sftp-hostkey
        secret:
          secretName: sftp-hostkey