apiVersion: v1
kind: Pod
metadata:
  name: sftp
  namespace: sftp
  labels:
    app: sftp
spec:
  containers:
  - name: sftp
    image: despitehowever/sftp:latest
    volumeMounts:
    - mountPath: /home/scanner/in
      name: scans-pvc
  volumes:
  - name: scans-pvc
    persistentVolumeClaim:
      claimName: unas-scans-ro-claim